package main

import (
	"flag"
	"fmt"
	"log"
	"os"
)

const (
	bytesPerLine = 0xFFFF_FFFF
)

var inputFile string
var outputFile string
var pkgName string
var varName string

func init() {
	flag.StringVar(&inputFile, "input", "", "input file")
	flag.StringVar(&outputFile, "output", "", "output file")
	flag.StringVar(&varName, "var", "", "variable name")
	flag.StringVar(&pkgName, "package", varName, "package name")
	flag.Parse()
}

func main() {
	data, err := os.ReadFile(inputFile)
	if err != nil {
		log.Fatalf("Error reading input file: %v", err)
	}

	out, err := os.Create(outputFile)
	if err != nil {
		log.Fatalf("Error creating output file: %v", err)
	}
	defer out.Close()

	fmt.Fprintln(out, "// Code generated by SiGo; DO NOT EDIT.\n")
	fmt.Fprintf(out, "package %s\n\n", pkgName)

	fmt.Fprintf(out, "const %s =\n", varName)
	for i := 0; i < len(data); i += bytesPerLine {
		end := i + bytesPerLine
		terminator := "+"
		if end > len(data) {
			end = len(data)
			terminator = ""
		}
		fmt.Fprint(out, "\t\"")
		for j := i; j < end; j++ {
			fmt.Fprintf(out, "\\x%02x", data[j])
		}
		fmt.Fprintln(out, "\""+terminator)
	}

	fmt.Println("Generated", outputFile, "with", len(data), "bytes.")
}
