package builder

import (
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path"
	"path/filepath"

	"omibyte.io/sigo/targets"
)

const (
	picolibcH = `
/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

/* Use atomics for fgetc/ungetc for re-entrancy */
#define ATOMIC_UNGETC

/* Always optimize strcmp for performance */
#define FAST_STRCMP

/* Obsoleted. Use regular syscalls */
/* #undef MISSING_SYSCALL_NAMES */

/* use global errno variable */
/* #undef NEWLIB_GLOBAL_ERRNO */

/* use function to get errno address */
/* #undef __PICOLIBC_ERRNO_FUNCTION */

/* use thread local storage */
/* #undef NEWLIB_TLS */

/* use thread local storage */
/* #undef PICOLIBC_TLS */

/* Use open/close/read/write in tinystdio */
#define POSIX_IO

/* Use posix apis for console too */
/* #undef POSIX_CONSOLE */

/* Optimize for space over speed */
/* #undef PREFER_SIZE_OVER_SPEED */

/* Obsoleted. Reentrant syscalls provided for us */
/* #undef REENTRANT_SYSCALLS_PROVIDED */

/* Use tiny stdio from gcc avr */
#define TINY_STDIO

/* #undef _ATEXIT_DYNAMIC_ALLOC */

/* #undef _FSEEK_OPTIMIZATION */

/* #undef _FVWRITE_IN_STREAMIO */

#define _HAVE_ALIAS_ATTRIBUTE

/* The compiler REALLY has the attribute __alloc_size__ */
#define _HAVE_ALLOC_SIZE

/* The compiler supports the always_inline function attribute */
#define _HAVE_ATTRIBUTE_ALWAYS_INLINE

/* The compiler supports the gnu_inline function attribute */
#define _HAVE_ATTRIBUTE_GNU_INLINE

/* Use bitfields in packed structs */
#define _HAVE_BITFIELDS_IN_PACKED_STRUCTS

/* The compiler supports __builtin_alloca */
#define _HAVE_BUILTIN_ALLOCA

/* The compiler supports __builtin_copysign */
#define _HAVE_BUILTIN_COPYSIGN

/* The compiler supports __builtin_copysignl */
#define _HAVE_BUILTIN_COPYSIGNL

/* The compiler supports __builtin_ctz */
#define _HAVE_BUILTIN_CTZ

/* The compiler supports __builtin_ctzl */
#define _HAVE_BUILTIN_CTZL

/* The compiler supports __builtin_ctzll */
#define _HAVE_BUILTIN_CTZLL

/* Compiler has __builtin_expect */
#define _HAVE_BUILTIN_EXPECT

/* The compiler supports __builtin_ffs */
#define _HAVE_BUILTIN_FFS

/* The compiler supports __builtin_ffsl */
#define _HAVE_BUILTIN_FFSL

/* The compiler supports __builtin_ffsll */
#define _HAVE_BUILTIN_FFSLL

/* The compiler supports __builtin_finitel */
/* #undef _HAVE_BUILTIN_FINITEL */

/* The compiler supports __builtin_isfinite */
#define _HAVE_BUILTIN_ISFINITE

/* The compiler supports __builtin_isinf */
#define _HAVE_BUILTIN_ISINF

/* The compiler supports __builtin_isinfl */
/* #undef _HAVE_BUILTIN_ISINFL */

/* The compiler supports __builtin_isnan */
#define _HAVE_BUILTIN_ISNAN

/* The compiler supports __builtin_isnanl */
/* #undef _HAVE_BUILTIN_ISNANL */

/* Compiler has __builtin_mul_overflow */
#define _HAVE_BUILTIN_MUL_OVERFLOW

/* Compiler has __builtin_add_overflow */
#define _HAVE_BUILTIN_ADD_OVERFLOW

/* Compiler flag to prevent detecting memcpy/memset patterns */
/* #undef _HAVE_CC_INHIBIT_LOOP_TO_LIBCALL */

/* Compiler supports _Complex */
#define _HAVE_COMPLEX

/* Compiler supports __builtin_complex */
#define _HAVE_BUILTIN_COMPLEX

/* #undef _HAVE_FCNTL */

#define _HAVE_FORMAT_ATTRIBUTE

/* IEEE fp funcs available */
/* #undef _HAVE_IEEEFP_FUNCS */

/* compiler supports INIT_ARRAY sections */
#define _HAVE_INITFINI_ARRAY

/* Support _init() and _fini() functions */
#define _HAVE_INIT_FINI

/* Compiler has long double type */
#define _HAVE_LONG_DOUBLE

/* Compiler attribute to prevent the optimizer from adding new builtin calls */
#define _HAVE_NO_BUILTIN_ATTRIBUTE

/* _set_tls and _init_tls functions available */
/* #undef _HAVE_PICOLIBC_TLS_API */

/* Semihost APIs supported */
#define _HAVE_SEMIHOST

#define _HAVE_WEAK_ATTRIBUTE

/* #undef _ICONV_ENABLE_EXTERNAL_CCS */

#define _ICONV_FROM_ENCODING_

#define _ICONV_FROM_ENCODING_BIG5

#define _ICONV_FROM_ENCODING_CP775

#define _ICONV_FROM_ENCODING_CP850

#define _ICONV_FROM_ENCODING_CP852

#define _ICONV_FROM_ENCODING_CP855

#define _ICONV_FROM_ENCODING_CP866

#define _ICONV_FROM_ENCODING_EUC_JP

#define _ICONV_FROM_ENCODING_EUC_KR

#define _ICONV_FROM_ENCODING_EUC_TW

#define _ICONV_FROM_ENCODING_ISO_8859_1

#define _ICONV_FROM_ENCODING_ISO_8859_10

#define _ICONV_FROM_ENCODING_ISO_8859_11

#define _ICONV_FROM_ENCODING_ISO_8859_13

#define _ICONV_FROM_ENCODING_ISO_8859_14

#define _ICONV_FROM_ENCODING_ISO_8859_15

#define _ICONV_FROM_ENCODING_ISO_8859_2

#define _ICONV_FROM_ENCODING_ISO_8859_3

#define _ICONV_FROM_ENCODING_ISO_8859_4

#define _ICONV_FROM_ENCODING_ISO_8859_5

#define _ICONV_FROM_ENCODING_ISO_8859_6

#define _ICONV_FROM_ENCODING_ISO_8859_7

#define _ICONV_FROM_ENCODING_ISO_8859_8

#define _ICONV_FROM_ENCODING_ISO_8859_9

#define _ICONV_FROM_ENCODING_ISO_IR_111

#define _ICONV_FROM_ENCODING_KOI8_R

#define _ICONV_FROM_ENCODING_KOI8_RU

#define _ICONV_FROM_ENCODING_KOI8_U

#define _ICONV_FROM_ENCODING_KOI8_UNI

#define _ICONV_FROM_ENCODING_UCS_2

#define _ICONV_FROM_ENCODING_UCS_2BE

#define _ICONV_FROM_ENCODING_UCS_2LE

#define _ICONV_FROM_ENCODING_UCS_2_INTERNAL

#define _ICONV_FROM_ENCODING_UCS_4

#define _ICONV_FROM_ENCODING_UCS_4BE

#define _ICONV_FROM_ENCODING_UCS_4LE

#define _ICONV_FROM_ENCODING_UCS_4_INTERNAL

#define _ICONV_FROM_ENCODING_US_ASCII

#define _ICONV_FROM_ENCODING_UTF_16

#define _ICONV_FROM_ENCODING_UTF_16BE

#define _ICONV_FROM_ENCODING_UTF_16LE

#define _ICONV_FROM_ENCODING_UTF_8

#define _ICONV_FROM_ENCODING_WIN_1250

#define _ICONV_FROM_ENCODING_WIN_1251

#define _ICONV_FROM_ENCODING_WIN_1252

#define _ICONV_FROM_ENCODING_WIN_1253

#define _ICONV_FROM_ENCODING_WIN_1254

#define _ICONV_FROM_ENCODING_WIN_1255

#define _ICONV_FROM_ENCODING_WIN_1256

#define _ICONV_FROM_ENCODING_WIN_1257

#define _ICONV_FROM_ENCODING_WIN_1258

#define _ICONV_TO_ENCODING_

#define _ICONV_TO_ENCODING_BIG5

#define _ICONV_TO_ENCODING_CP775

#define _ICONV_TO_ENCODING_CP850

#define _ICONV_TO_ENCODING_CP852

#define _ICONV_TO_ENCODING_CP855

#define _ICONV_TO_ENCODING_CP866

#define _ICONV_TO_ENCODING_EUC_JP

#define _ICONV_TO_ENCODING_EUC_KR

#define _ICONV_TO_ENCODING_EUC_TW

#define _ICONV_TO_ENCODING_ISO_8859_1

#define _ICONV_TO_ENCODING_ISO_8859_10

#define _ICONV_TO_ENCODING_ISO_8859_11

#define _ICONV_TO_ENCODING_ISO_8859_13

#define _ICONV_TO_ENCODING_ISO_8859_14

#define _ICONV_TO_ENCODING_ISO_8859_15

#define _ICONV_TO_ENCODING_ISO_8859_2

#define _ICONV_TO_ENCODING_ISO_8859_3

#define _ICONV_TO_ENCODING_ISO_8859_4

#define _ICONV_TO_ENCODING_ISO_8859_5

#define _ICONV_TO_ENCODING_ISO_8859_6

#define _ICONV_TO_ENCODING_ISO_8859_7

#define _ICONV_TO_ENCODING_ISO_8859_8

#define _ICONV_TO_ENCODING_ISO_8859_9

#define _ICONV_TO_ENCODING_ISO_IR_111

#define _ICONV_TO_ENCODING_KOI8_R

#define _ICONV_TO_ENCODING_KOI8_RU

#define _ICONV_TO_ENCODING_KOI8_U

#define _ICONV_TO_ENCODING_KOI8_UNI

#define _ICONV_TO_ENCODING_UCS_2

#define _ICONV_TO_ENCODING_UCS_2BE

#define _ICONV_TO_ENCODING_UCS_2LE

#define _ICONV_TO_ENCODING_UCS_2_INTERNAL

#define _ICONV_TO_ENCODING_UCS_4

#define _ICONV_TO_ENCODING_UCS_4BE

#define _ICONV_TO_ENCODING_UCS_4LE

#define _ICONV_TO_ENCODING_UCS_4_INTERNAL

#define _ICONV_TO_ENCODING_US_ASCII

#define _ICONV_TO_ENCODING_UTF_16

#define _ICONV_TO_ENCODING_UTF_16BE

#define _ICONV_TO_ENCODING_UTF_16LE

#define _ICONV_TO_ENCODING_UTF_8

#define _ICONV_TO_ENCODING_WIN_1250

#define _ICONV_TO_ENCODING_WIN_1251

#define _ICONV_TO_ENCODING_WIN_1252

#define _ICONV_TO_ENCODING_WIN_1253

#define _ICONV_TO_ENCODING_WIN_1254

#define _ICONV_TO_ENCODING_WIN_1255

#define _ICONV_TO_ENCODING_WIN_1256

#define _ICONV_TO_ENCODING_WIN_1257

#define _ICONV_TO_ENCODING_WIN_1258

/* math library does not set errno (offering only ieee semantics) */
#define _IEEE_LIBM

#define _IO_FLOAT_EXACT

#define _LITE_EXIT

/* #undef _MB_CAPABLE */

#define _MB_LEN_MAX 1

/* #undef _NANO_FORMATTED_IO */

#define _NANO_MALLOC

/* The newlib version in string format. */
#define _NEWLIB_VERSION "4.3.0"

#define _PICO_EXIT

/* The Picolibc minor version number. */
#define _PICOLIBC_MINOR__ 8

/* The Picolibc version in string format. */
#define _PICOLIBC_VERSION "1.8.3"

/* The Picolibc major version number. */
#define _PICOLIBC__ 1

/* #undef _REENT_GLOBAL_ATEXIT */

#define _RETARGETABLE_LOCKING

/* #undef _UNBUF_STREAM_OPT */

#define _WANT_IO_C99_FORMATS

/* #undef _WANT_IO_LONG_LONG */

/* #undef _WANT_IO_POS_ARGS */

/* #undef FORMAT_DEFAULT_DOUBLE */

/* #undef FORMAT_DEFAULT_FLOAT */

#define FORMAT_DEFAULT_INTEGER

/* math library sets errno */
/* #undef _WANT_MATH_ERRNO */

/* #undef _WANT_REENT_SMALL */

/* #undef _WANT_REGISTER_FINI */

/* Obsoleted. Define time_t to long instead of using a 64-bit type */
/* #undef _WANT_USE_LONG_TIME_T */

/* #undef _WIDE_ORIENT */

/* extended locale support */
/* #undef __HAVE_LOCALE_INFO_EXTENDED__ */

/* locale support */
/* #undef __HAVE_LOCALE_INFO__ */

/* The newlib minor version number. */
#define __NEWLIB_MINOR__ 3

/* The newlib patch level. */
#define __NEWLIB_PATCHLEVEL__ 0

/* The newlib major version number. */
#define __NEWLIB__ 4

/* Use old math code */
#define __OBSOLETE_MATH_FLOAT 1

#define __OBSOLETE_MATH_DOUBLE 1

/* Compute static memory area sizes at runtime instead of link time */
/* #undef __PICOLIBC_CRT_RUNTIME_SIZE */

/* The Picolibc minor version number. */
#define __PICOLIBC_MINOR__ 8

/* The Picolibc patch level. */
#define __PICOLIBC_PATCHLEVEL__ 3

/* The Picolibc version in string format. */
#define __PICOLIBC_VERSION__ "1.8.3"

/* The Picolibc major version number. */
#define __PICOLIBC__ 1

/* #undef __SINGLE_THREAD__ */

/* Compiler has Xtensa-specific core-isa.h header file */
/* #undef _XTENSA_HAVE_CONFIG_CORE_ISA_H */
`
)

type Package struct {
	PathPrefix  string
	Sources     []string
	IncludeDirs []string
	Defines     []string
	Files       map[string]string
}

func (p *Package) Compile(toolchain Toolchain, target targets.TargetInfo, debug bool, opt string, outputDir string) ([]string, error) {
	var artifacts []string
	var defines []string

	includes := []string{"-I" + outputDir}

	// Create files.
	for p, content := range p.Files {
		fname := filepath.Join(outputDir, p)
		err := os.MkdirAll(filepath.Dir(fname), os.ModePerm)
		if err != nil {
			return nil, err
		}

		err = os.WriteFile(fname, []byte(content), 0644)
		if err != nil {
			return nil, err
		}
	}

	for _, include := range p.IncludeDirs {
		includes = append(includes, fmt.Sprintf("-I%s", include))
	}

	for _, define := range p.Defines {
		defines = append(defines, fmt.Sprintf("-D%s", define))
	}

	for _, src := range p.Sources {
		artifact := filepath.Join(outputDir, filepath.Dir(src), filepath.Base(src)+".o")

		// Create the directory to where the artifact should be stored.
		err := os.MkdirAll(filepath.Dir(artifact), os.ModePerm)
		if err != nil {
			return nil, err
		}

		args := []string{
			fmt.Sprintf("--target=%s", target.Triplet),
		}
		args = append(args, includes...)
		args = append(args, defines...)

		if debug {
			args = append(args, "-g")
		}

		switch opt {
		case "0":
			args = append(args, "-O0")
		case "1":
			args = append(args, "-O1")
		case "2":
			args = append(args, "-O2")
		case "3":
			args = append(args, "-O3")
		case "s":
			args = append(args, "-Os")
		case "z":
			args = append(args, "-Oz")
		case "d":
			args = append(args, "-O0")
		default:
			args = append(args, "-O0")
		}

		args = append(args,
			"-c", "-o", artifact,
			path.Join(p.PathPrefix, src),
		)
		cmd := exec.Command(toolchain.CC, args...)
		cmd.Stdout = os.Stdout
		cmd.Stderr = os.Stderr
		cmd.Stdin = os.Stdin
		if err := cmd.Run(); err != nil {
			fmt.Println()
			fmt.Println("Command failed: ", cmd.String())
			return nil, errors.Join(ErrCompilerFailed, err)
		}
		artifacts = append(artifacts, artifact)
	}
	return artifacts, nil
}

func pkgPicolibc(target targets.TargetInfo) (Package, error) {
	env, err := Environment()
	if err != nil {
		return Package{}, err
	}

	prefix := path.Join(env["SIGOROOT"], "thirdparty", "picolibc")
	pkg := Package{
		PathPrefix: prefix,
		IncludeDirs: []string{
			path.Join(prefix, "newlib/libc/include"),
			path.Join(prefix, "newlib/libc/stdio"),
			path.Join(prefix, "picocrt"),
		},
		Files: map[string]string{
			"picolibc.h": picolibcH,
		},
		Sources: []string{
			"newlib/libc/errno/errno.c",
			"newlib/libc/misc/init.c",
			"newlib/libc/misc/lock.c",
			"newlib/libc/picolib/picosbrk.c",
			"newlib/libc/stdlib/abort.c",
			"newlib/libc/stdlib/exit.c",
			"newlib/libc/stdlib/nano-malloc-calloc.c",
			"newlib/libc/stdlib/nano-malloc-cfree.c",
			"newlib/libc/stdlib/nano-malloc-free.c",
			"newlib/libc/stdlib/nano-malloc-mallinfo.c",
			"newlib/libc/stdlib/nano-malloc-malloc.c",
			"newlib/libc/stdlib/nano-malloc-malloc_stats.c",
			"newlib/libc/stdlib/nano-malloc-malloc_usable_size.c",
			"newlib/libc/stdlib/nano-malloc-mallopt.c",
			"newlib/libc/stdlib/nano-malloc-memalign.c",
			"newlib/libc/stdlib/nano-malloc-pvalloc.c",
			"newlib/libc/stdlib/nano-malloc-realloc.c",
			"newlib/libc/stdlib/nano-malloc-valloc.c",
			"newlib/libc/string/memcpy.c",
			"newlib/libc/string/strncmp.c",
			"newlib/libc/string/strncpy.c",
		},
	}

	switch target.Architecture {
	case "arm", "thumb":
		pkg.Sources = append(pkg.Sources,
			"newlib/libc/machine/arm/memchr.S",
			"newlib/libc/machine/arm/memmove.c",
			"newlib/libc/machine/arm/memset.c",
			"newlib/libc/machine/arm/setjmp.S",
			"newlib/libc/machine/arm/strcmp.S",
			"newlib/libc/machine/arm/strcpy.S",
			"newlib/libc/machine/arm/strlen.c",
			"newlib/libc/machine/arm/strlen.S",
		)
	}

	return pkg, nil
}
